### ISSUE TITLE
Attention

### ISSUE THREAD

**Issue by kudryashovda** [Kalhoznik123/MD5_password_generator#2]
https://github.com/Kalhoznik123/MD5_password_generator/blob/e411894beb4b49703a20aa8057670e32ed4fb0b9/password_builder.cpp#L49
Опасная операция result.begin() + password_size_. Если в будущем изменится логика GenerateRandomString в сторону больших длин, то можно получить выход за пределы контейнера

**Comment by Kalhoznik123** [comment]
А можно тут поподробнее)) Я в самом начале функции постарался учесть этот момент, при помощи проверки. 

> https://github.com/Kalhoznik123/MD5_password_generator/blob/e411894beb4b49703a20aa8057670e32ed4fb0b9/password_builder.cpp#L49
> 
> 
> Опасная операция result.begin() + password_size_. Если в будущем изменится логика GenerateRandomString в сторону больших длин, то можно получить выход за пределы контейнера
